# Generated by Django 4.2.28 on 2026-02-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_adhesion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
